### ISSUE TITLE
On va dire que j'ai pas vu pour l'instant...

### ISSUE THREAD

**Issue by davidmarsprof** [Corentin1998/Pong#1]
Corentin, commente un peu ton code js stp, ça m'embêterai de pas te mettre les deux points alors que tu as fait l'effort nickel sur la CSS.

**Comment by Corentin1998** [comment]
Bonjour monsieur, je viens de rajouter deux commentaires sur le js.

Le ven. 6 nov. 2020 à 15:40, davidmarsprof <notifications@github.com> a
écrit :
